-- GENERATED by tools/build-content — DO NOT EDIT BY HAND.
-- Source: research/. Regenerate with: python3 tools/build-content/build.py
-- Derived from the TWRPG dataset by sfarmani (github.com/sfarmani/twrpg-info)
-- and the map by Keekero / greenFruit. See research/raw/PROVENANCE.md.

local Stacking = {
	NOTE = "within a (kind, slot) only the strongest applies; across slots they multiply; Stackable sums. See docs/00 §3.2.",
	slots = {
		{
			kind = "Damage Dealt",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Sword Enchanter - Power Enchant [E] (Buff) - 5%",
					magnitude = 0.05,
					owner = "Sword Enchanter",
					trigger = "buff",
				},
				{
					source = "Witch - Mark of Power [T] -> [W] (Buff) - 5%",
					magnitude = 0.05,
					owner = "Witch",
					trigger = "buff",
				},
				{
					source = "Priest - Heaven Field [F] (Buff) - 5%",
					magnitude = 0.05,
					owner = "Priest",
					trigger = "buff",
				},
				{
					source = "Paladin - Genesis [F] (Buff) - 8%",
					magnitude = 0.08,
					owner = "Paladin",
					trigger = "buff",
				},
			},
		},
		{
			kind = "Damage Dealt",
			slot = "Type-B",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "The Ender - 15%",
					magnitude = 0.15,
					owner = "The Ender",
				},
				{
					source = "Heartrender - 15%",
					magnitude = 0.15,
					owner = "Heartrender",
				},
				{
					source = "Ring of Malevolence - 10%",
					magnitude = 0.1,
					owner = "Ring of Malevolence",
				},
			},
		},
		{
			kind = "Attack Damage",
			slot = "Type-A",
			suffix = "Fixed",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Azathos, the Pipe of Chaos (Aura)",
				},
				{
					source = "Horn of God (Aura)",
				},
			},
		},
		{
			kind = "Attack Damage",
			slot = "Type-B",
			suffix = "Percentage",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Sword Enchanter - Power Enchant [E] (Buff) - 20%",
					magnitude = 0.2,
					owner = "Sword Enchanter",
					trigger = "buff",
				},
				{
					source = "Blood Weaver - Blood Boil [R] (Buff) - 20%",
					magnitude = 0.2,
					owner = "Blood Weaver",
					trigger = "buff",
				},
			},
		},
		{
			kind = "Attack Damage",
			slot = "Type-C",
			suffix = "Percentage",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Paladin - Aura of Retribution [D] → [Q] - 10%",
					magnitude = 0.1,
					owner = "Paladin",
				},
				{
					source = "Bow Master - Guardian Scout [E] - 8%",
					magnitude = 0.08,
					owner = "Bow Master",
				},
			},
		},
		{
			kind = "Attack Damage",
			slot = "Type-D",
			suffix = "Percentage",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Eye of the Flame Lord (Aura) - 5%",
					magnitude = 0.05,
					owner = "Eye of the Flame Lord (Aura)",
				},
			},
		},
		{
			kind = "Attack Speed",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = { {
					source = "Lifestone (Aura)",
				} },
		},
		{
			kind = "Attack Speed",
			slot = "Type-B",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Azathos, the Pipe of Chaos (Aura)",
				},
				{
					source = "Horn of God (Aura)",
				},
			},
		},
		{
			kind = "Skill Damage (Staff)",
			slot = "Type-B",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Staff of Void (Buff)",
					trigger = "buff",
				},
				{
					source = "Staff of Madness (Buff)",
					trigger = "buff",
				},
				{
					source = "Staff of Abyss (Buff)",
					trigger = "buff",
				},
				{
					source = "Soul of Abyss (Buff)",
					trigger = "buff",
				},
				{
					source = "Gate of Abyss (Buff)",
					trigger = "buff",
				},
			},
		},
		{
			kind = "Skill Damage (Gun)",
			slot = "Type-B",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Red Cross (Buff)",
					trigger = "buff",
				},
				{
					source = "Crimson Cross (Buff)",
					trigger = "buff",
				},
				{
					source = "Crimson Star (Buff)",
					trigger = "buff",
				},
				{
					source = "Cosmic Star (Buff)",
					trigger = "buff",
				},
				{
					source = "Abyss Fall (Buff)",
					trigger = "buff",
				},
			},
		},
		{
			kind = "Skill Damage",
			slot = "Type-C",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Eye of the Abyss (Aura)",
				},
				{
					source = "Void Eye (Aura)",
				},
				{
					source = "Eye of the Flame Lord (Aura)",
				},
			},
		},
		{
			kind = "Skill Damage",
			slot = "Stackable",
			suffix = "None",
			polarity = "buff",
			stackable = true,
			sources = {
				{
					source = "Paladin - Aura of Retribution (Sigil Aura)",
					owner = "Paladin",
				},
				{
					source = "Bag of Hell - Throwing Healing Potion (W) Specialty",
					owner = "Bag of Hell",
				},
				{
					source = "Bag of Corruption - Throwing Healing Potion (W) Specialty",
					owner = "Bag of Corruption",
				},
				{
					source = "Bag of Destruction - Throwing Healing Potion (W) Specialty",
					owner = "Bag of Destruction",
				},
				{
					source = "Bag of Demise - Throwing Healing Potion (W) Specialty",
					owner = "Bag of Demise",
				},
				{
					source = "Diana, the Robe of Holy Maiden (Aura) - 6%",
					magnitude = 0.06,
					owner = "Diana, the Robe of Holy Maiden (Aura)",
				},
				{
					source = "Jupiter, the Robe of Heavens (Aura) - 8%",
					magnitude = 0.08,
					owner = "Jupiter, the Robe of Heavens (Aura)",
				},
			},
		},
		{
			kind = "Magic Defense",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Diana, the Robe of Holy Maiden (Aura) - 8%",
					magnitude = 0.08,
					owner = "Diana, the Robe of Holy Maiden (Aura)",
				},
				{
					source = "Jupiter, the Robe of Heavens (Aura) - 10%",
					magnitude = 0.1,
					owner = "Jupiter, the Robe of Heavens (Aura)",
				},
				{
					source = "Oath of Courage (Aura) - 8%",
					magnitude = 0.08,
					owner = "Oath of Courage (Aura)",
				},
				{
					source = "Eternal Rose (Aura) - 8%",
					magnitude = 0.08,
					owner = "Eternal Rose (Aura)",
				},
				{
					source = "Nebula Rose (Aura) - 10%",
					magnitude = 0.1,
					owner = "Nebula Rose (Aura)",
				},
				{
					source = "Arch Druid Robe (Aura) - 10%",
					magnitude = 0.1,
					owner = "Arch Druid Robe (Aura)",
				},
			},
		},
		{
			kind = "Reduced damage received",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Ispion, the Runed Ring (Aura) - 6%",
					magnitude = 0.06,
					owner = "Ispion, the Runed Ring (Aura)",
				},
				{
					source = "Nebula Rose (Active) - 12%",
					magnitude = 0.12,
					owner = "Nebula Rose (Active)",
					trigger = "active",
				},
				{
					source = "Heirloom of Lazarus (Active) - 15%",
					magnitude = 0.15,
					owner = "Heirloom of Lazarus (Active)",
					trigger = "active",
				},
				{
					source = "Keeper of the Grove (Earth Seed Aura) - 20%",
					magnitude = 0.2,
					owner = "Keeper of the Grove (Earth Seed Aura)",
				},
			},
		},
		{
			kind = "Healing Received",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Ispion, the Runed Ring (Aura) - 12%",
					magnitude = 0.12,
					owner = "Ispion, the Runed Ring (Aura)",
				},
				{
					source = "Protection of the Fairies (Aura) - 15%",
					magnitude = 0.15,
					owner = "Protection of the Fairies (Aura)",
				},
				{
					source = "Thread of Life (Aura) - 15%",
					magnitude = 0.15,
					owner = "Thread of Life (Aura)",
				},
			},
		},
		{
			kind = "All Stats",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Purelight Armor (Aura) - 4%",
					magnitude = 0.04,
					owner = "Purelight Armor (Aura)",
				},
				{
					source = "Requiem, the Armor of Lamentation (Aura) - 5%",
					magnitude = 0.05,
					owner = "Requiem, the Armor of Lamentation (Aura)",
				},
				{
					source = "Hades, the Armor of Despair (Aura) - 6%",
					magnitude = 0.06,
					owner = "Hades, the Armor of Despair (Aura)",
				},
				{
					source = "Cage of Twisted Souls (Aura) - 7%",
					magnitude = 0.07,
					owner = "Cage of Twisted Souls (Aura)",
				},
				{
					source = "Arch Druid Robe (Aura) - (10%)",
					owner = "Arch Druid Robe (Aura)",
				},
			},
		},
		{
			kind = "All Stats",
			slot = "Type-B",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Elementalist - Refreshing Well [W] → [Passive] (Aura) - (10% allies)",
					owner = "Elementalist",
				},
				{
					source = "Lancer - Meteor Spear [T] → [Active] - (10% allies)",
					owner = "Lancer",
				},
				{
					source = "Crusader - Flash of Immortality [W] → [Passive] (Aura) - (10% self - 5% allies)",
					owner = "Crusader",
				},
			},
		},
		{
			kind = "HP Regen",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Azathos, the Pipe of Chaos (Aura)",
				},
				{
					source = "Horn of God (Aura)",
				},
			},
		},
		{
			kind = "Main Stat",
			slot = "Type-A",
			suffix = "None",
			polarity = "buff",
			stackable = false,
			sources = {
				{
					source = "Heaven's Door - (60 + 3%)",
					owner = "Heaven's Door",
				},
				{
					source = "Guardian Angel (Aura) - (80 + 4%)",
					owner = "Guardian Angel (Aura)",
				},
				{
					source = "Aeon Sphere - (150 + 3%)",
					owner = "Aeon Sphere",
				},
			},
		},
		{
			kind = "Armor Reduction",
			slot = "Type-A",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Corruptor (Passive)",
					trigger = "passive",
				},
				{
					source = "Anger (Passive) - 15%",
					magnitude = 0.15,
					owner = "Anger (Passive)",
					trigger = "passive",
				},
				{
					source = "Oblivion (Passive) - 15%",
					magnitude = 0.15,
					owner = "Oblivion (Passive)",
					trigger = "passive",
				},
				{
					source = "Desolation (Passive) - 15%",
					magnitude = 0.15,
					owner = "Desolation (Passive)",
					trigger = "passive",
				},
				{
					source = "Chaos (Passive) - 15%",
					magnitude = 0.15,
					owner = "Chaos (Passive)",
					trigger = "passive",
				},
				{
					source = "Heart of Ifrit (Passive) - 12%",
					magnitude = 0.12,
					owner = "Heart of Ifrit (Passive)",
					trigger = "passive",
				},
				{
					source = "Frost Web Brooch (Passive) - 12%",
					magnitude = 0.12,
					owner = "Frost Web Brooch (Passive)",
					trigger = "passive",
				},
				{
					source = "Fairy Robe - Fairy Fire (Active)",
					owner = "Fairy Robe",
					trigger = "active",
				},
				{
					source = "Horns of Destruction (Active)",
					trigger = "active",
				},
				{
					source = "Heaven's Fist (Passive) - 15%",
					magnitude = 0.15,
					owner = "Heaven's Fist (Passive)",
					trigger = "passive",
				},
				{
					source = "Demonic Fist (Passive) - 15%",
					magnitude = 0.15,
					owner = "Demonic Fist (Passive)",
					trigger = "passive",
				},
			},
		},
		{
			kind = "Armor Reduction",
			slot = "Type-B",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Guardian of the Skies (Active) - 20%",
					magnitude = 0.2,
					owner = "Guardian of the Skies (Active)",
					trigger = "active",
				},
				{
					source = "Ruler of the Skies (Active) - 20%",
					magnitude = 0.2,
					owner = "Ruler of the Skies (Active)",
					trigger = "active",
				},
			},
		},
		{
			kind = "Armor Reduction",
			slot = "Type-C",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Martial Artist - Vacuum Palm (Passive) - 15%",
					magnitude = 0.15,
					owner = "Martial Artist",
					trigger = "passive",
				},
			},
		},
		{
			kind = "Increased Magic Damage taken",
			slot = "Type-A",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Staff of Souls (Active)",
					trigger = "active",
				},
				{
					source = "Hell Riser (Active)",
					trigger = "active",
				},
				{
					source = "Armageddon (Active)",
					trigger = "active",
				},
				{
					source = "Prelude to Demise (Active)",
					trigger = "active",
				},
				{
					source = "Eyes of the Watcher (Active)",
					trigger = "active",
				},
			},
		},
		{
			kind = "Increased Magic Damage taken",
			slot = "Type-B",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Ring of Composure (Passive)",
					trigger = "passive",
				},
				{
					source = "Ring of Despair (Passive)",
					trigger = "passive",
				},
				{
					source = "Cloak of the Fallen Shadows (Passive)",
					trigger = "passive",
				},
				{
					source = "Cape of Deep Abyss (Passive)",
					trigger = "passive",
				},
			},
		},
		{
			kind = "Increased Magic Damage taken",
			slot = "Type-C",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Soul Weaver - Astral Walk (Active)",
					owner = "Soul Weaver",
					trigger = "active",
				},
				{
					source = "Elementalist - Charge (Passive)",
					owner = "Elementalist",
					trigger = "passive",
				},
				{
					source = "Berserker - Howling [W] (Active)",
					owner = "Berserker",
					trigger = "active",
				},
			},
		},
		{
			kind = "Increased Damage Taken",
			slot = "Type-A",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Lancer - Pierce [Q]",
					owner = "Lancer",
				},
				{
					source = "Crusader - Empowered Strike of Honor [R] → [R] → [E]",
					owner = "Crusader",
				},
				{
					source = "Swordsman - Illusal Dance [T]",
					owner = "Swordsman",
				},
				{
					source = "Alchemist - Rolling Golem [R] → [R] → [W]",
					owner = "Alchemist",
				},
				{
					source = "Fighter - Chain Blow [E]",
					owner = "Fighter",
				},
			},
		},
		{
			kind = "Increased Damage Taken",
			slot = "Type-B",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Hades, the Armor of Despair [Passive]",
				},
				{
					source = "Cage of Twisted Souls (4% [Passive], 8% [Active])",
				},
			},
		},
		{
			kind = "Increased Damage Taken",
			slot = "Type-C",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Shooter - Distortion [R]",
					owner = "Shooter",
				},
				{
					source = "Paladin - Divine Cross [R]",
					owner = "Paladin",
				},
			},
		},
		{
			kind = "Increased Damage Taken",
			slot = "Type-D",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = { {
					source = "Soul Weaver - Unholy Blast [Q]",
					owner = "Soul Weaver",
				} },
		},
		{
			kind = "Reduced Healing Received",
			slot = "Type-A",
			suffix = "None",
			polarity = "debuff",
			stackable = false,
			sources = {
				{
					source = "Parasitic Staff (Active)",
					trigger = "active",
				},
				{
					source = "Staff of Plague (Active)",
					trigger = "active",
				},
				{
					source = "Merchant - Throw Money [R]",
					owner = "Merchant",
				},
				{
					source = "Sword Enchanter - Ultimate Enchant [F]",
					owner = "Sword Enchanter",
				},
			},
		},
	},
	byKind = {
		["Damage Dealt"] = {
			{
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 4,
			},
			{
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 3,
			},
		},
		["Attack Damage"] = {
			{
				slot = "Type-A",
				suffix = "Fixed",
				stackable = false,
				sourceCount = 2,
			},
			{
				slot = "Type-B",
				suffix = "Percentage",
				stackable = false,
				sourceCount = 2,
			},
			{
				slot = "Type-C",
				suffix = "Percentage",
				stackable = false,
				sourceCount = 2,
			},
			{
				slot = "Type-D",
				suffix = "Percentage",
				stackable = false,
				sourceCount = 1,
			},
		},
		["Attack Speed"] = {
			{
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 1,
			},
			{
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 2,
			},
		},
		["Skill Damage (Staff)"] = { {
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 5,
			} },
		["Skill Damage (Gun)"] = { {
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 5,
			} },
		["Skill Damage"] = {
			{
				slot = "Type-C",
				suffix = "None",
				stackable = false,
				sourceCount = 3,
			},
			{
				slot = "Stackable",
				suffix = "None",
				stackable = true,
				sourceCount = 7,
			},
		},
		["Magic Defense"] = { {
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 6,
			} },
		["Reduced damage received"] = { {
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 4,
			} },
		["Healing Received"] = { {
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 3,
			} },
		["All Stats"] = {
			{
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 5,
			},
			{
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 3,
			},
		},
		["HP Regen"] = { {
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 2,
			} },
		["Main Stat"] = { {
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 3,
			} },
		["Armor Reduction"] = {
			{
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 11,
			},
			{
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 2,
			},
			{
				slot = "Type-C",
				suffix = "None",
				stackable = false,
				sourceCount = 1,
			},
		},
		["Increased Magic Damage taken"] = {
			{
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 5,
			},
			{
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 4,
			},
			{
				slot = "Type-C",
				suffix = "None",
				stackable = false,
				sourceCount = 3,
			},
		},
		["Increased Damage Taken"] = {
			{
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 5,
			},
			{
				slot = "Type-B",
				suffix = "None",
				stackable = false,
				sourceCount = 2,
			},
			{
				slot = "Type-C",
				suffix = "None",
				stackable = false,
				sourceCount = 2,
			},
			{
				slot = "Type-D",
				suffix = "None",
				stackable = false,
				sourceCount = 1,
			},
		},
		["Reduced Healing Received"] = { {
				slot = "Type-A",
				suffix = "None",
				stackable = false,
				sourceCount = 4,
			} },
	},
	bySource = {
		["Sword Enchanter - Power Enchant [E] (Buff) - 5%"] = { {
				kind = "Damage Dealt",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Witch - Mark of Power [T] -> [W] (Buff) - 5%"] = { {
				kind = "Damage Dealt",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Priest - Heaven Field [F] (Buff) - 5%"] = { {
				kind = "Damage Dealt",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Paladin - Genesis [F] (Buff) - 8%"] = { {
				kind = "Damage Dealt",
				slot = "Type-A",
				polarity = "buff",
			} },
		["The Ender - 15%"] = { {
				kind = "Damage Dealt",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Heartrender - 15%"] = { {
				kind = "Damage Dealt",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Ring of Malevolence - 10%"] = { {
				kind = "Damage Dealt",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Azathos, the Pipe of Chaos (Aura)"] = {
			{
				kind = "Attack Damage",
				slot = "Type-A",
				polarity = "buff",
			},
			{
				kind = "Attack Speed",
				slot = "Type-B",
				polarity = "buff",
			},
			{
				kind = "HP Regen",
				slot = "Type-A",
				polarity = "buff",
			},
		},
		["Horn of God (Aura)"] = {
			{
				kind = "Attack Damage",
				slot = "Type-A",
				polarity = "buff",
			},
			{
				kind = "Attack Speed",
				slot = "Type-B",
				polarity = "buff",
			},
			{
				kind = "HP Regen",
				slot = "Type-A",
				polarity = "buff",
			},
		},
		["Sword Enchanter - Power Enchant [E] (Buff) - 20%"] = { {
				kind = "Attack Damage",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Blood Weaver - Blood Boil [R] (Buff) - 20%"] = { {
				kind = "Attack Damage",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Paladin - Aura of Retribution [D] → [Q] - 10%"] = { {
				kind = "Attack Damage",
				slot = "Type-C",
				polarity = "buff",
			} },
		["Bow Master - Guardian Scout [E] - 8%"] = { {
				kind = "Attack Damage",
				slot = "Type-C",
				polarity = "buff",
			} },
		["Eye of the Flame Lord (Aura) - 5%"] = { {
				kind = "Attack Damage",
				slot = "Type-D",
				polarity = "buff",
			} },
		["Lifestone (Aura)"] = { {
				kind = "Attack Speed",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Staff of Void (Buff)"] = { {
				kind = "Skill Damage (Staff)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Staff of Madness (Buff)"] = { {
				kind = "Skill Damage (Staff)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Staff of Abyss (Buff)"] = { {
				kind = "Skill Damage (Staff)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Soul of Abyss (Buff)"] = { {
				kind = "Skill Damage (Staff)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Gate of Abyss (Buff)"] = { {
				kind = "Skill Damage (Staff)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Red Cross (Buff)"] = { {
				kind = "Skill Damage (Gun)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Crimson Cross (Buff)"] = { {
				kind = "Skill Damage (Gun)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Crimson Star (Buff)"] = { {
				kind = "Skill Damage (Gun)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Cosmic Star (Buff)"] = { {
				kind = "Skill Damage (Gun)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Abyss Fall (Buff)"] = { {
				kind = "Skill Damage (Gun)",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Eye of the Abyss (Aura)"] = { {
				kind = "Skill Damage",
				slot = "Type-C",
				polarity = "buff",
			} },
		["Void Eye (Aura)"] = { {
				kind = "Skill Damage",
				slot = "Type-C",
				polarity = "buff",
			} },
		["Eye of the Flame Lord (Aura)"] = { {
				kind = "Skill Damage",
				slot = "Type-C",
				polarity = "buff",
			} },
		["Paladin - Aura of Retribution (Sigil Aura)"] = { {
				kind = "Skill Damage",
				slot = "Stackable",
				polarity = "buff",
			} },
		["Bag of Hell - Throwing Healing Potion (W) Specialty"] = { {
				kind = "Skill Damage",
				slot = "Stackable",
				polarity = "buff",
			} },
		["Bag of Corruption - Throwing Healing Potion (W) Specialty"] = { {
				kind = "Skill Damage",
				slot = "Stackable",
				polarity = "buff",
			} },
		["Bag of Destruction - Throwing Healing Potion (W) Specialty"] = { {
				kind = "Skill Damage",
				slot = "Stackable",
				polarity = "buff",
			} },
		["Bag of Demise - Throwing Healing Potion (W) Specialty"] = { {
				kind = "Skill Damage",
				slot = "Stackable",
				polarity = "buff",
			} },
		["Diana, the Robe of Holy Maiden (Aura) - 6%"] = { {
				kind = "Skill Damage",
				slot = "Stackable",
				polarity = "buff",
			} },
		["Jupiter, the Robe of Heavens (Aura) - 8%"] = { {
				kind = "Skill Damage",
				slot = "Stackable",
				polarity = "buff",
			} },
		["Diana, the Robe of Holy Maiden (Aura) - 8%"] = { {
				kind = "Magic Defense",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Jupiter, the Robe of Heavens (Aura) - 10%"] = { {
				kind = "Magic Defense",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Oath of Courage (Aura) - 8%"] = { {
				kind = "Magic Defense",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Eternal Rose (Aura) - 8%"] = { {
				kind = "Magic Defense",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Nebula Rose (Aura) - 10%"] = { {
				kind = "Magic Defense",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Arch Druid Robe (Aura) - 10%"] = { {
				kind = "Magic Defense",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Ispion, the Runed Ring (Aura) - 6%"] = { {
				kind = "Reduced damage received",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Nebula Rose (Active) - 12%"] = { {
				kind = "Reduced damage received",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Heirloom of Lazarus (Active) - 15%"] = { {
				kind = "Reduced damage received",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Keeper of the Grove (Earth Seed Aura) - 20%"] = { {
				kind = "Reduced damage received",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Ispion, the Runed Ring (Aura) - 12%"] = { {
				kind = "Healing Received",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Protection of the Fairies (Aura) - 15%"] = { {
				kind = "Healing Received",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Thread of Life (Aura) - 15%"] = { {
				kind = "Healing Received",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Purelight Armor (Aura) - 4%"] = { {
				kind = "All Stats",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Requiem, the Armor of Lamentation (Aura) - 5%"] = { {
				kind = "All Stats",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Hades, the Armor of Despair (Aura) - 6%"] = { {
				kind = "All Stats",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Cage of Twisted Souls (Aura) - 7%"] = { {
				kind = "All Stats",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Arch Druid Robe (Aura) - (10%)"] = { {
				kind = "All Stats",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Elementalist - Refreshing Well [W] → [Passive] (Aura) - (10% allies)"] = { {
				kind = "All Stats",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Lancer - Meteor Spear [T] → [Active] - (10% allies)"] = { {
				kind = "All Stats",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Crusader - Flash of Immortality [W] → [Passive] (Aura) - (10% self - 5% allies)"] = { {
				kind = "All Stats",
				slot = "Type-B",
				polarity = "buff",
			} },
		["Heaven's Door - (60 + 3%)"] = { {
				kind = "Main Stat",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Guardian Angel (Aura) - (80 + 4%)"] = { {
				kind = "Main Stat",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Aeon Sphere - (150 + 3%)"] = { {
				kind = "Main Stat",
				slot = "Type-A",
				polarity = "buff",
			} },
		["Corruptor (Passive)"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Anger (Passive) - 15%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Oblivion (Passive) - 15%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Desolation (Passive) - 15%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Chaos (Passive) - 15%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Heart of Ifrit (Passive) - 12%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Frost Web Brooch (Passive) - 12%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Fairy Robe - Fairy Fire (Active)"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Horns of Destruction (Active)"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Heaven's Fist (Passive) - 15%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Demonic Fist (Passive) - 15%"] = { {
				kind = "Armor Reduction",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Guardian of the Skies (Active) - 20%"] = { {
				kind = "Armor Reduction",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Ruler of the Skies (Active) - 20%"] = { {
				kind = "Armor Reduction",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Martial Artist - Vacuum Palm (Passive) - 15%"] = { {
				kind = "Armor Reduction",
				slot = "Type-C",
				polarity = "debuff",
			} },
		["Staff of Souls (Active)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Hell Riser (Active)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Armageddon (Active)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Prelude to Demise (Active)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Eyes of the Watcher (Active)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Ring of Composure (Passive)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Ring of Despair (Passive)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Cloak of the Fallen Shadows (Passive)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Cape of Deep Abyss (Passive)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Soul Weaver - Astral Walk (Active)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-C",
				polarity = "debuff",
			} },
		["Elementalist - Charge (Passive)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-C",
				polarity = "debuff",
			} },
		["Berserker - Howling [W] (Active)"] = { {
				kind = "Increased Magic Damage taken",
				slot = "Type-C",
				polarity = "debuff",
			} },
		["Lancer - Pierce [Q]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Crusader - Empowered Strike of Honor [R] → [R] → [E]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Swordsman - Illusal Dance [T]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Alchemist - Rolling Golem [R] → [R] → [W]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Fighter - Chain Blow [E]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Hades, the Armor of Despair [Passive]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Cage of Twisted Souls (4% [Passive], 8% [Active])"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-B",
				polarity = "debuff",
			} },
		["Shooter - Distortion [R]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-C",
				polarity = "debuff",
			} },
		["Paladin - Divine Cross [R]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-C",
				polarity = "debuff",
			} },
		["Soul Weaver - Unholy Blast [Q]"] = { {
				kind = "Increased Damage Taken",
				slot = "Type-D",
				polarity = "debuff",
			} },
		["Parasitic Staff (Active)"] = { {
				kind = "Reduced Healing Received",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Staff of Plague (Active)"] = { {
				kind = "Reduced Healing Received",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Merchant - Throw Money [R]"] = { {
				kind = "Reduced Healing Received",
				slot = "Type-A",
				polarity = "debuff",
			} },
		["Sword Enchanter - Ultimate Enchant [F]"] = { {
				kind = "Reduced Healing Received",
				slot = "Type-A",
				polarity = "debuff",
			} },
	},
}

return Stacking
