#!/usr/bin/env python3
"""Shared loading, normalisation and emit helpers for the content build.

Source of truth is `research/` (read-only). Nothing in this package may edit it.
Everything under `game/dota_addons/championrpg/scripts/npc/` and `.../vscripts/data/`
is generated and must never be hand-edited.
"""
import json
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RAW = os.path.join(ROOT, "research", "raw")
EXTRACTED = os.path.join(ROOT, "research", "extracted")
ADDON = os.path.join(ROOT, "game", "dota_addons", "championrpg")
NPC = os.path.join(ADDON, "scripts", "npc")
VSCRIPTS = os.path.join(ADDON, "scripts", "vscripts")
DATA = os.path.join(VSCRIPTS, "data")

GENERATED_HEADER = (
    "// GENERATED by tools/build-content — DO NOT EDIT BY HAND.\n"
    "// Source: research/. Regenerate with: python3 tools/build-content/build.py\n"
)
LUA_HEADER = (
    "-- GENERATED by tools/build-content — DO NOT EDIT BY HAND.\n"
    "-- Source: research/. Regenerate with: python3 tools/build-content/build.py\n"
)


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def raw(name):
    return load(os.path.join(RAW, name))


def extracted(name):
    return load(os.path.join(EXTRACTED, name))


# --------------------------------------------------------------- name handling

COLOUR_RX = re.compile(r"\|c[0-9a-fA-F]{8}|\|[rRnN]")


def strip_colour(s):
    """Warcraft III colour codes are embedded in every name string."""
    return COLOUR_RX.sub("", s or "").strip()


def slug(name):
    """Stable, unique-ish identifier fragment for a display name."""
    s = strip_colour(name).lower()
    s = re.sub(r"['\u2019\u00b4`]", "", s)
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return re.sub(r"_+", "_", s).strip("_")


def unit_key(name):
    return "npc_championrpg_" + slug(name)


def item_key(name):
    return "item_championrpg_" + slug(name)


def ability_key(name):
    return "championrpg_" + slug(name)


def hero_key(hero_class):
    return "npc_dota_hero_championrpg_" + slug(hero_class)


# ------------------------------------------------------------------ numbers

def num(v, default=0.0):
    """TWRPG data stores numbers as strings, sometimes '.5' or ''."""
    if v is None:
        return default
    if isinstance(v, (int, float)):
        return float(v)
    s = str(v).strip().replace(",", "")
    if not s:
        return default
    try:
        return float(s)
    except ValueError:
        return default


def as_int(v, default=0):
    return int(round(num(v, default)))


def fmt(v):
    """Render a float without a pointless trailing .0 (KV files are strings)."""
    f = num(v)
    return str(int(f)) if f == int(f) else ("%g" % f)


# ------------------------------------------------------------------- emitters

def write_kv(path, root_key, entries, header=GENERATED_HEADER):
    """Emit a Valve KeyValues file. `entries` is {block_name: {k: v | dict}}."""
    def block(d, indent):
        pad = "\t" * indent
        out = []
        for k, v in d.items():
            if isinstance(v, dict):
                out.append('%s"%s"' % (pad, k))
                out.append("%s{" % pad)
                out.extend(block(v, indent + 1))
                out.append("%s}" % pad)
            else:
                out.append('%s"%s"%s"%s"' % (pad, k, "\t" * max(1, 4 - len(k) // 8), v))
        return out

    lines = [header, '"%s"' % root_key, "{"]
    for name, body in entries.items():
        lines.append('\t"%s"' % name)
        lines.append("\t{")
        lines.extend(block(body, 2))
        lines.append("\t}")
        lines.append("")
    lines.append("}")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return len(entries)


def _lua_value(v, indent):
    pad = "\t" * indent
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return fmt(v) if isinstance(v, float) else str(v)
    if v is None:
        return "nil"
    if isinstance(v, str):
        return '"%s"' % v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    if isinstance(v, list):
        if not v:
            return "{}"
        inner = ", ".join(_lua_value(x, indent + 1) for x in v)
        if len(inner) < 100:
            return "{ %s }" % inner
        parts = ["{"]
        parts += ["%s\t%s," % (pad, _lua_value(x, indent + 1)) for x in v]
        parts.append("%s}" % pad)
        return "\n".join(parts)
    if isinstance(v, dict):
        if not v:
            return "{}"
        parts = ["{"]
        for k, val in v.items():
            key = k if re.match(r"^[A-Za-z_]\w*$", str(k)) else '["%s"]' % k
            parts.append("%s\t%s = %s," % (pad, key, _lua_value(val, indent + 1)))
        parts.append("%s}" % pad)
        return "\n".join(parts)
    raise TypeError("cannot serialise %r" % type(v))


def write_lua_table(path, varname, data, header=LUA_HEADER):
    """Emit a Lua module returning a table."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("\nlocal %s = %s\n\nreturn %s\n" % (varname, _lua_value(data, 0), varname))
    return len(data)
