#!/usr/bin/env python3
"""Render the ability->handler mapping as browsable markdown.

Usage: python3 report_abilities.py <ability_map.json> <skills.json> <out.md>
"""
import json
import re
import sys
from collections import defaultdict

EVENT_SHORT = {
    "EVENT_PLAYER_UNIT_SPELL_EFFECT": "cast:effect",
    "EVENT_PLAYER_UNIT_SPELL_CHANNEL": "cast:channel",
    "EVENT_PLAYER_UNIT_SPELL_CAST": "cast:start",
    "EVENT_PLAYER_UNIT_SPELL_ENDCAST": "cast:end",
    "EVENT_PLAYER_HERO_SKILL": "on-learn",
    "EVENT_PLAYER_UNIT_USE_ITEM": "item:use",
    "EVENT_PLAYER_UNIT_PICKUP_ITEM": "item:pickup",
    "EVENT_PLAYER_UNIT_SELL_ITEM": "item:sell",
    "EVENT_PLAYER_UNIT_SUMMON": "on-summon",
}


def _call_span(s, start):
    """Given index of '(' at `start`, return index just past its matching ')'."""
    depth = 0
    for i in range(start, len(s)):
        if s[i] == "(":
            depth += 1
        elif s[i] == ")":
            depth -= 1
            if depth == 0:
                return i + 1
    return -1


def _replace_call(s, name, render):
    """Replace every `name(...)` call using a balanced-paren scan.

    A regex cannot do this safely: the arguments themselves contain nested
    parentheses, and a greedy match swallows delimiters belonging to the
    surrounding expression.
    """
    out, i = [], 0
    while True:
        j = s.find(name + "(", i)
        if j < 0:
            out.append(s[i:])
            return "".join(out)
        end = _call_span(s, j + len(name))
        if end < 0:
            out.append(s[i:])
            return "".join(out)
        out.append(s[i:j])
        out.append(render(s[j + len(name) + 1:end - 1]))
        i = end


def tidy(expr):
    """Make a mangled JASS expression readable without inventing meaning.

    Only mechanical substitutions: hero-stat accessors become STR/AGI/INT and
    GetUnitUserData becomes `uid`. Everything else is left verbatim.
    """
    e = expr
    for fn, stat in (("GetHeroStr", "STR"), ("GetHeroAgi", "AGI"), ("GetHeroInt", "INT")):
        e = _replace_call(e, fn, lambda _a, s=stat: s)
    e = _replace_call(e, "GetUnitUserData", lambda a: "uid(%s)" % a.strip("()"))
    e = re.sub(r"\s+", " ", e)
    return e.strip()


def main():
    map_file, skills_file, out = sys.argv[1], sys.argv[2], sys.argv[3]
    rows = json.load(open(map_file))
    skills = json.load(open(skills_file))
    order = {s["id"]: s.get("order", 0) for s in skills}

    per_class = defaultdict(list)
    items, bosses, other = [], [], []
    for r in rows:
        if r.get("heroClass"):
            per_class[r["heroClass"]].append(r)
        elif r["kind"] == "item":
            items.append(r)
        elif r.get("caster"):
            bosses.append(r)
        else:
            other.append(r)

    L = ["# Mangled Function → Named Ability Map", "",
         "Recovered by resolving the spell-registry bindings in the protected script.",
         "`handler` is the obfuscated JASS function that implements the ability.",
         "Formulas are verbatim expressions from that function (stat names substituted in).",
         "", "Generated by `tools/extract-w3x/map_abilities.py` + `report_abilities.py`.", ""]

    L += ["## Summary", "",
          "| | Count |", "|---|---|",
          "| Registrations resolved | %d |" % len(rows),
          "| Distinct rawcodes | %d |" % len({r["rawcode"] for r in rows}),
          "| Distinct handler functions | %d |" % len({r["handler"] for r in rows}),
          "| Hero-ability registrations | %d |" % sum(len(v) for v in per_class.values()),
          "| Item registrations | %d |" % len(items),
          "| Boss-ability registrations | %d |" % len(bosses),
          "| With extracted stat formulas | %d |" % sum(1 for r in rows if r.get("statFormulas")),
          ""]

    L += ["## Hero abilities", ""]
    for cls in sorted(per_class):
        rs = sorted(per_class[cls], key=lambda r: (order.get(r["rawcode"], 99),
                                                   r["rawcode"], r["handler"]))
        L += ["### %s  (%d registrations)" % (cls, len(rs)), "",
              "| Ability | Key | Rawcode | Handler | Bound on | Formulas |",
              "|---|---|---|---|---|---|"]
        for r in rs:
            ev = ", ".join(EVENT_SHORT.get(e, e) for e in r["events"]) or "internal"
            f = r.get("statFormulas") or []
            fs = "<br>".join("`%s`" % tidy(x).replace("|", "\\|")[:150] for x in f[:3]) or "—"
            L.append("| %s | %s | `%s` | `%s` | %s | %s |" % (
                r.get("communityName") or r.get("mapName") or "?",
                r.get("hotkey") or "", r["rawcode"], r["handler"], ev, fs))
        L.append("")

    if bosses:
        L += ["## Boss abilities", "",
              "| Ability | Caster | Rawcode | Handler | Bound on |", "|---|---|---|---|---|"]
        for r in sorted(bosses, key=lambda r: (r.get("caster") or "", r["rawcode"])):
            ev = ", ".join(EVENT_SHORT.get(e, e) for e in r["events"]) or "internal"
            L.append("| %s | %s | `%s` | `%s` | %s |" % (
                r.get("communityName") or r.get("mapName") or "?",
                r.get("caster") or "", r["rawcode"], r["handler"], ev))
        L.append("")

    L += ["## Item-triggered abilities", "",
          "| Item | Rawcode | Handler | Bound on |", "|---|---|---|---|"]
    for r in sorted(items, key=lambda r: (r.get("mapName") or "", r["rawcode"])):
        ev = ", ".join(EVENT_SHORT.get(e, e) for e in r["events"]) or "internal"
        L.append("| %s | `%s` | `%s` | %s |" % (
            r.get("communityName") or r.get("mapName") or "?",
            r["rawcode"], r["handler"], ev))
    L.append("")

    if other:
        L += ["## Unclassified registrations", "",
              "| Name | Kind | Rawcode | Handler | Bound on |", "|---|---|---|---|---|"]
        for r in sorted(other, key=lambda r: r["rawcode"]):
            ev = ", ".join(EVENT_SHORT.get(e, e) for e in r["events"]) or "internal"
            L.append("| %s | %s | `%s` | `%s` | %s |" % (
                r.get("mapName") or "?", r["kind"], r["rawcode"], r["handler"], ev))
        L.append("")

    open(out, "w").write("\n".join(L) + "\n")
    print("wrote %s (%d lines)" % (out, len(L)))


if __name__ == "__main__":
    main()
