-- GENERATED by tools/build-content — DO NOT EDIT BY HAND.
-- Source: research/. Regenerate with: python3 tools/build-content/build.py

local Encounters = {
	npc_twrpg_silverback_wolf = {
		unit = "npc_twrpg_silverback_wolf",
		displayName = "Silverback Wolf",
		tier = "Creep",
		level = 10,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Summon Shadow Wolf", "Critical Strike" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_shadow_wolf" },
		partyLimit = 1,
		enrageTimer = 60,
		bark = "Grr..",
	},
	npc_twrpg_troll_lord = {
		unit = "npc_twrpg_troll_lord",
		displayName = "Troll Lord",
		tier = "Creep",
		level = 20,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Mirror Image" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		enrageTimer = 90,
	},
	npc_twrpg_furbolg_giant = {
		unit = "npc_twrpg_furbolg_giant",
		displayName = "Furbolg Giant",
		tier = "Creep",
		level = 29,
		authored = false,
		phases = { {
				at = 1,
				abilities = {},
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		enrageTimer = 60,
	},
	npc_twrpg_protector_of_nature = {
		unit = "npc_twrpg_protector_of_nature",
		displayName = "Protector of Nature",
		tier = "Field",
		level = 30,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Wrath of Nature", "Shackle of Nature" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 2,
		bark = "The nature purges you!",
	},
	npc_twrpg_dragon_turtle = {
		unit = "npc_twrpg_dragon_turtle",
		displayName = "Dragon Turtle",
		tier = "Creep",
		level = 45,
		authored = false,
		phases = { {
				at = 1,
				abilities = {},
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		enrageTimer = 120,
	},
	npc_twrpg_king_crab = {
		unit = "npc_twrpg_king_crab",
		displayName = "King Crab",
		tier = "Field",
		level = 40,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Harden Shell", "Sea Wave", "Hold" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		bark = "MRGLMRGL",
	},
	npc_twrpg_walrus = {
		unit = "npc_twrpg_walrus",
		displayName = "Walrus",
		tier = "Field",
		level = 40,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Slimy Ball", "Slippery Skin", "Headbutt" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		bark = "It's slippery..",
	},
	npc_twrpg_polar_bear_giant = {
		unit = "npc_twrpg_polar_bear_giant",
		displayName = "Polar Bear Giant",
		tier = "Creep",
		level = 50,
		authored = false,
		phases = { {
				at = 1,
				abilities = {},
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		enrageTimer = 120,
	},
	npc_twrpg_mammoth = {
		unit = "npc_twrpg_mammoth",
		displayName = "Mammoth",
		tier = "Field",
		level = 50,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Massive Tusk", "Charge", "Hailstorm" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		bark = "BARANG",
	},
	npc_twrpg_king_kong = {
		unit = "npc_twrpg_king_kong",
		displayName = "King Kong",
		tier = "Field",
		level = 50,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Enrage", "Throw" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		bark = "Monke.",
	},
	npc_twrpg_wallachia_death_knight_lord = {
		unit = "npc_twrpg_wallachia_death_knight_lord",
		displayName = "Wallachia Death Knight Lord",
		tier = "Creep",
		level = 60,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Dark Strength", "Death Finger", "Summon Wraith" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_wraith" },
		partyLimit = 5,
		enrageTimer = 240,
	},
	npc_twrpg_blood_wraith = {
		unit = "npc_twrpg_blood_wraith",
		displayName = "Blood Wraith",
		tier = "Field",
		level = 60,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Bloody Echoes", "Blood Anger", "Craze", "True Requiem" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_soldier_of_blood" },
		partyLimit = 2,
		bark = "I shall be unleashed!!",
	},
	npc_twrpg_wallachia_monstrosity = {
		unit = "npc_twrpg_wallachia_monstrosity",
		displayName = "Wallachia Monstrosity",
		tier = "Field",
		level = 60,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Death Cross", "Summon Bat Statue", "Hear me out!", "Desperate Flight" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_bat_statue" },
		partyLimit = 2,
		bark = "Bats! Bats! BATS!",
	},
	npc_twrpg_lava_ancient = {
		unit = "npc_twrpg_lava_ancient",
		displayName = "Lava Ancient",
		tier = "Creep",
		level = 68,
		authored = false,
		phases = { {
				at = 1,
				abilities = {},
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 1,
		enrageTimer = 30,
	},
	npc_twrpg_ruler_of_flames_ragnaar = {
		unit = "npc_twrpg_ruler_of_flames_ragnaar",
		displayName = "Ruler of Flames Ragnaar",
		tier = "Creep",
		level = 70,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Craze", "Hellflame Nova", "Slaves of Trueflame" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_slave_of_trueflame" },
		partyLimit = 2,
		enrageTimer = 90,
	},
	npc_twrpg_evil_lava_spawn = {
		unit = "npc_twrpg_evil_lava_spawn",
		displayName = "Evil Lava Spawn",
		tier = "Field",
		level = 70,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Fireball Barrage", "Evil Power", "Seal", "Nyohoho", "How fun!" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 2,
		bark = "Nyohoho!!",
	},
	npc_twrpg_tentacle_lord = {
		unit = "npc_twrpg_tentacle_lord",
		displayName = "Tentacle Lord",
		tier = "Creep",
		level = 80,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Tentacle Slam", "Tentacle Spike", "Tentacles" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 5,
		enrageTimer = 90,
	},
	npc_twrpg_guardian_of_sea = {
		unit = "npc_twrpg_guardian_of_sea",
		displayName = "Guardian of Sea",
		tier = "Field",
		level = 80,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Sea Beam", "Summon Bubble", "Water Splash", "The Sea will Shallow You!" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 2,
		bark = "Feel the might of sea!",
	},
	npc_twrpg_giant_golem = {
		unit = "npc_twrpg_giant_golem",
		displayName = "Giant Golem",
		tier = "Creep",
		level = 90,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Crushing Slam", "Unstoppable Force" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 2,
		enrageTimer = 90,
	},
	npc_twrpg_mana_ancient = {
		unit = "npc_twrpg_mana_ancient",
		displayName = "Mana Ancient",
		tier = "Creep",
		level = 90,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Mana Swipe", "Drain", "Mana Explosion" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 2,
		enrageTimer = 90,
	},
	npc_twrpg_ruler_of_the_lav_sea_hydra = {
		unit = "npc_twrpg_ruler_of_the_lav_sea_hydra",
		displayName = "Ruler of the Lav Sea Hydra",
		tier = "Minor",
		level = 50,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Lethal Poison", "Stomp", "Sea Wave" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 5,
		respawnMinutes = 4,
		bark = "grwwowowrwo !",
	},
	npc_twrpg_duchy_of_wallachia_count = {
		unit = "npc_twrpg_duchy_of_wallachia_count",
		displayName = "Duchy of Wallachia Count",
		tier = "Minor",
		level = 60,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Immortal Body", "Death Bind", "Hounds of Berskubil", "Requiem of BLood", "Unleash True Form" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 5,
		respawnMinutes = 5,
		bark = "The night begins now !",
	},
	npc_twrpg_jack_o_lantern = {
		unit = "npc_twrpg_jack_o_lantern",
		displayName = "Jack o Lantern",
		tier = "Minor",
		level = 60,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Jack Impact", "Jack Wave", "Pumpkin Body" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 3,
		respawnMinutes = 5,
		bark = "..It's not Halloween yet !",
	},
	npc_twrpg_mage_lord = {
		unit = "npc_twrpg_mage_lord",
		displayName = "Mage Lord",
		tier = "Minor",
		level = 70,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Blizzard", "Chain Lightning", "Dark Star", "Magical Weapon" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 4,
		respawnMinutes = 5,
		bark = "I shall give you a taste of my magic!",
	},
	npc_twrpg_wings_of_death = {
		unit = "npc_twrpg_wings_of_death",
		displayName = "Wings of Death",
		tier = "Minor",
		level = 70,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Dragon Breath", "Dragon Fear", "Hell Flame", "Dragon's Might" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 5,
		respawnMinutes = 5,
		bark = "Feel the might of dragons !",
	},
	npc_twrpg_castle_avalon_gatekeeper = {
		unit = "npc_twrpg_castle_avalon_gatekeeper",
		displayName = "Castle Avalon Gatekeeper",
		tier = "Minor",
		level = 80,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Genocide Sword", "Nanoscale Armor" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		respawnMinutes = 5,
		bark = "...",
	},
	npc_twrpg_the_3rd_armys_guardian_angel = {
		unit = "npc_twrpg_the_3rd_armys_guardian_angel",
		displayName = "The 3rd Army's Guardian Angel",
		tier = "Minor",
		level = 80,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Blessed Wings", "Holy Grab", "Sacred Conviction", "Sacred Judgment" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 4,
		respawnMinutes = 5,
		bark = "Behold, your end is nigh !",
	},
	npc_twrpg_the_devils_right_arm_corrupt_angel = {
		unit = "npc_twrpg_the_devils_right_arm_corrupt_angel",
		displayName = "The Devil's Right Arm Corrupt Angel",
		tier = "Minor",
		level = 80,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Hell Finger", "Craze", "Judgment of Darkness", "Dark Wings", "Darkness Wave" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 4,
		respawnMinutes = 5,
		bark = "Die !!",
	},
	npc_twrpg_wallachia_mad_clown = {
		unit = "npc_twrpg_wallachia_mad_clown",
		displayName = "Wallachia Mad Clown",
		tier = "Minor",
		level = 100,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Instincts", "Darkness Wave", "Mirror Image", "Mad Howl", "Wheel of Fate" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 3,
		respawnMinutes = 4,
		bark = "Dance !",
	},
	npc_twrpg_soul_of_everfrost = {
		unit = "npc_twrpg_soul_of_everfrost",
		displayName = "Soul of Everfrost",
		tier = "Minor",
		level = 90,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Hellfrost Nova", "Frozen Soul" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_frozen_soul" },
		partyLimit = 4,
		respawnMinutes = 4,
		bark = "Freeze !!",
	},
	npc_twrpg_frostspider_queen = {
		unit = "npc_twrpg_frostspider_queen",
		displayName = "Frostspider Queen",
		tier = "Minor",
		level = 90,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Frost Aura", "Frost Spike" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 4,
		respawnMinutes = 4,
		bark = "Kiiik !!",
	},
	npc_twrpg_frostspider_lord = {
		unit = "npc_twrpg_frostspider_lord",
		displayName = "Frostspider Lord",
		tier = "Minor",
		level = 90,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Frozen Barrier", "Frozen Shatter", "Ice Storm", "Hellfrost Body", "Web Binding" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 4,
		respawnMinutes = 4,
		bark = "Be purged by Frost !!",
	},
	npc_twrpg_demon_lord_beriel = {
		unit = "npc_twrpg_demon_lord_beriel",
		displayName = "Demon Lord Beriel",
		tier = "Minor",
		level = 90,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Rage", "The Demon Lord's Power", "Seal", "Meteor", "Destruction", "Catacylsm" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_hell_golem" },
		partyLimit = 4,
		respawnMinutes = 4,
		bark = "It's time for your doom !",
		needsScriptedHook = "wave phase gated on not killing the gate",
	},
	npc_twrpg_spirit_beast = {
		unit = "npc_twrpg_spirit_beast",
		displayName = "Spirit Beast",
		tier = "Mid",
		level = 100,
		authored = false,
		phases = { {
				at = 1,
				abilities = { "Ethreal Strike", "Spirit Echo", "Drain", "Heaven's Wrath" },
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		partyLimit = 3,
		respawnMinutes = 4,
		bark = "Oh Heaven, Aid Me!",
	},
	npc_twrpg_corruptor_rectus = {
		unit = "npc_twrpg_corruptor_rectus",
		displayName = "Corruptor Rectus",
		tier = "Mid",
		level = 100,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Corrupt Power",
					"Corruption",
					"Death Coil",
					"Soul Swap",
					"Corruption Overload",
					"Corruption Aura",
					"Corrupted Summoning",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_stalker", "npc_twrpg_avenger", "npc_twrpg_life_orb" },
		partyLimit = 5,
		respawnMinutes = 4,
		bark = "Welcome to your ceremony of death!",
	},
	npc_twrpg_flame_nightmare = {
		unit = "npc_twrpg_flame_nightmare",
		displayName = "Flame Nightmare",
		tier = "Mid",
		level = 100,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Nightmare Body", "Overload", "Flame Barrage", "On Your Knees!", "Total Annihilation" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_flame_spawn", "npc_twrpg_anger", "npc_twrpg_hatred" },
		partyLimit = 4,
		respawnMinutes = 4,
		bark = "Fall on your knees!",
	},
	npc_twrpg_turtle_lord = {
		unit = "npc_twrpg_turtle_lord",
		displayName = "Turtle Lord",
		tier = "Mid",
		level = 100,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Hard Shell",
					"Turtle Ambush",
					"Summon Healing Turtle",
					"Mystic Shell",
					"Chomp Armor",
					"Mana Bombardment",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_turtle", "npc_twrpg_healing_turtle" },
		partyLimit = 4,
		respawnMinutes = 4,
		bark = "Gurgle!",
	},
	npc_twrpg_bone_dragon = {
		unit = "npc_twrpg_bone_dragon",
		displayName = "Bone Dragon",
		tier = "High",
		level = 110,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Swipe", "Flame Breath", "Hell Spike", "Petrification", "Dragon's Rage" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_flame_spirit" },
		respawnMinutes = 3,
		bark = "I'll show you my true powers!",
	},
	npc_twrpg_skeletal_king_desperia = {
		unit = "npc_twrpg_skeletal_king_desperia",
		displayName = "Skeletal King Desperia",
		tier = "High",
		level = 110,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Super Armor",
					"Drain Soul",
					"Soul Terror",
					"Weapon of Nothingness",
					"Absolute Devastation",
					"True Power of Despair",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		respawnMinutes = 5,
		bark = "This is the difference between your power and mine!",
	},
	npc_twrpg_zombie_lord = {
		unit = "npc_twrpg_zombie_lord",
		displayName = "Zombie Lord",
		tier = "High",
		level = 110,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Hunger", "Infected Claw", "Infected Swipes", "Infest", "Aura of Death", "Immortality" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_zombie", "npc_twrpg_worshipper_of_immortality" },
		respawnMinutes = 5,
		bark = "None shall take my eternal life away!",
	},
	npc_twrpg_ancient_ent = {
		unit = "npc_twrpg_ancient_ent",
		displayName = "Ancient Ent",
		tier = "High",
		level = 110,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = { "Earth Slam", "Lightning Storm", "Ent Power", "Fortitude of Nature" },
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_elder_ent", "npc_twrpg_giant_ent", "npc_twrpg_ent" },
		respawnMinutes = 5,
		bark = "Feel the might of Mother Nature!",
		needsScriptedHook = "75M HP, domain-based mechanics",
	},
	npc_twrpg_archangel_samael = {
		unit = "npc_twrpg_archangel_samael",
		displayName = "Archangel Samael",
		tier = "High",
		level = 110,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Light Overload",
					"Focused Light",
					"Order of Light",
					"Spirit of Light",
					"Protection of Light",
					"Judgment",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		respawnMinutes = 5,
		bark = "You mortals cannot escape your fate!",
	},
	npc_twrpg_shadow_dragon_irbert = {
		unit = "npc_twrpg_shadow_dragon_irbert",
		displayName = "Shadow Dragon Irbert",
		tier = "High",
		level = 110,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Shadow Attack",
					"Dragonic Skin",
					"Shadow Breath",
					"Seal",
					"Shadow Rune",
					"Super Armor",
					"Illusions of Shadow",
					"Eternity Link",
					"Dark Blast",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_illusion_of_irbert", "npc_twrpg_illusion_of_irbert_large" },
		respawnMinutes = 5,
		bark = "Face your inner evils...",
	},
	npc_twrpg_death_fiend = {
		unit = "npc_twrpg_death_fiend",
		displayName = "Death Fiend",
		tier = "Late",
		level = 120,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Creeping Death",
					"Howl of Death",
					"Strike of Death",
					"Unholy Summoning",
					"Determination of Death",
					"Death Comes...",
					"Doom",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_death_huntress", "npc_twrpg_death_devourer", "npc_twrpg_death_weaver" },
		partyLimit = 4,
		respawnMinutes = 3,
		bark = "Resistance is futile!",
		needsScriptedHook = "Fog phase disables self-resurrection",
	},
	npc_twrpg_valtora = {
		unit = "npc_twrpg_valtora",
		displayName = "Valtora",
		tier = "Late",
		level = 120,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Magnetic Attraction",
					"Storm Hammer",
					"Servant of Lightning",
					"Wrath of Heaven",
					"Nasty Shock",
					"Windy Presence",
					"Electric Storm",
					"Rage of the Thunder God",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_servant_of_lightning_god" },
		respawnMinutes = 5,
		bark = "The skies shall judge you!",
	},
	npc_twrpg_ifrit = {
		unit = "npc_twrpg_ifrit",
		displayName = "Ifrit",
		tier = "Late",
		level = 120,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Explosive Strike",
					"Raging Flame",
					"Flame Meteor",
					"Seed of Flame",
					"Hellfire",
					"Hot Pursuit",
					"Volcanic Party",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_obsidian_golem", "npc_twrpg_lava_spirit" },
		respawnMinutes = 5,
		bark = "It's time for some serious fun...",
	},
	npc_twrpg_nereid = {
		unit = "npc_twrpg_nereid",
		displayName = "Nereid",
		tier = "Endgame",
		level = 120,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Aegis of Sea",
					"Water Barrage",
					"Might of Sea",
					"Purification of Water",
					"Water Binding",
					"Drown",
					"Bubble Breath",
					"Geyser",
					"Water splash",
					"Protection of Sea",
					"Consumption of the Sea",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_wavecaller", "npc_twrpg_large_wavecaller" },
		respawnMinutes = 5,
		bark = "The sea shall consume you!",
	},
	npc_twrpg_underlord_agareth = {
		unit = "npc_twrpg_underlord_agareth",
		displayName = "Underlord Agareth",
		tier = "Endgame",
		level = 120,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Ethreal Strike",
					"Color",
					"Fear",
					"Soul Burst",
					"Empowered Soul Burst",
					"Umbra Dance",
					"Empowered Umbra Dance",
					"Skewer",
					"Empowered Skewer",
					"Finger of Death",
					"Hunt",
					"It's Time to Hunt",
					"Demonic Portal",
					"Fear ",
					"Void Fall",
					"Abyssal Miasma",
					"Armageddon",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = { "npc_twrpg_gatekeeper_of_hell", "npc_twrpg_cursed_spirit", "npc_twrpg_hellspawn" },
		empowered = {
			damageResist = 75,
		},
		respawnMinutes = 4,
		bark = "The end is nigh!",
		needsScriptedHook = "instanced mini-game arena with its own units",
	},
	npc_twrpg_duke_lazarus = {
		unit = "npc_twrpg_duke_lazarus",
		displayName = "Duke Lazarus",
		tier = "Endgame",
		level = 130,
		authored = false,
		phases = {
			{
				at = 1,
				abilities = {
					"Blood Burst",
					"Blood Tendril",
					"Blood Drain",
					"Blood Plague",
					"Blood Sickness",
					"Blood Tentacles",
					"Blood Sacrifice",
					"Blood Explosion",
					"Blood Swipe",
					"Leap of Terror",
					"Blood Spike",
					"Blood Howl",
					"Empowered Blood Swipe",
					"Empowered Leap of Terror",
					"Empowered Blood Howl",
					"Blood Orb",
					"Blood Shield",
					"Bleeding",
				},
			},
		},
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		minionTypes = {
			"npc_twrpg_vampiric_monstrosity",
			"npc_twrpg_servant_of_blood",
			"npc_twrpg_blood_baron",
			"npc_twrpg_spike",
		},
		empowered = {
			damageResist = 40,
			attackDamage = 10392,
			attackRange = 250,
			attackSpeed = 1,
			moveSpeed = 500,
			magicResist = 15,
		},
		respawnMinutes = 3,
		bark = "Dance Mortals and delight me further!",
		needsScriptedHook = "second form 'Lord of Sacrifice' with a different stat block",
	},
	npc_twrpg_gaia = {
		unit = "npc_twrpg_gaia",
		displayName = "Gaia",
		tier = "Endgame",
		level = 130,
		authored = false,
		phases = { {
				at = 1,
				abilities = {},
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		empoweredUnknown = true,
		respawnMinutes = 3,
	},
	npc_twrpg_arcane_construct = {
		unit = "npc_twrpg_arcane_construct",
		displayName = "Arcane Construct",
		tier = "Endgame",
		level = 130,
		authored = false,
		phases = { {
				at = 1,
				abilities = {},
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		respawnMinutes = 3,
	},
	npc_twrpg_styrix_the_harvester_of_souls = {
		unit = "npc_twrpg_styrix_the_harvester_of_souls",
		displayName = "Styrix, the Harvester of Souls",
		tier = "Endgame",
		level = 130,
		authored = false,
		phases = { {
				at = 1,
				abilities = {},
			} },
		modes = {
			normal = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0,
				drops = true,
			},
			hard = {
				damageDealt = 1,
				damageTaken = 1,
				dropRateBonus = 0.5,
				damageResistBonus = 0.33,
				drops = true,
			},
			practice = {
				damageDealt = 0.25,
				damageTaken = 3,
				dropRateBonus = 0,
				drops = false,
			},
		},
		partyScaling = {
			["8-10"] = {
				addHealth = -0.25,
				runeDrain = -0.25,
			},
		},
		respawnMinutes = 3,
		needsScriptedHook = "heals from heroes who die outside the zone",
	},
}

return Encounters
